### ISSUE TITLE
Use 'Container' instead of 'Environment'?

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#132]
While discussing with @CVandiedonck and @Scaburet we were thinking that the word 'container' could be better than the word 'environment'.

As we discussed earlier with @jtpio, 'container' comes from 'Docker container' and represents a very technical object. But for IT-naive people, a container is also a box that you put things in. This idea of a 'box' is quite accurate since an environment contains kernels (Python, R, bash), libraries, programs (shipped via apt or conda), notebooks and files to analyse.

On the other hand, the word 'environment' could describe something else. For instance, RStudio is an integrated development environment for R.

Finally, we think that 'container' is probably better to describe a user environment:
- it is technically accurate, user environments are indeed true (Docker) containers
- for students and teachers that are not aware of Docker, a container represents a box with everything they need to work inside.

@jtpio what are your thoughts on this?

**Comment by jtpio** [comment]
We might still want to differentiate between `containers` and `images`.

- Images are the ready-to-use "boxes" that sit on the machine with all the dependencies
- Containers are ephemeral instances of these images that can be started and stopped

Would replacing "Environments" by "Images" be a reasonable alternative? This way the terminology really maps to Docker and could make the communication between all kind of users easier? (between those more familiar with Docker and those less familiar with Docker)

There was also some thoughts about this in a previous issue (environment vs images).

**Comment by pierrepo** [comment]
Hum, actually I think container vs image is also a matter of user point-of-view.
A teacher creates environments that are Docker images.
A student uses environments that are Docker containers.

**Comment by pierrepo** [comment]
The word "Environment" is now widely used in the project. We should close this issue.

**Comment by CVandiedonck** [comment]
I agree
