### ISSUE TITLE
Create ansible task to get device name for quota

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#138]
As specified in the doc, one has to run the following command on the host to get device name:
```
cat /etc/fstab
```
To stay in line with the current strategy to handle hosts, one could use ansible instead.

An ad-hoc command could be:
```
$ ansible -i hosts -u ubuntu -m command -a "cat /etc/fstab" -o
``` 
But for some reason, this command does not work...

Another alternative could be to create dedicated task in the playbook `quotas.yml`:
```
    - name: List mounted devices on hosts
      shell: cat /etc/fstab
      register: fstab
      tags:
        - run
        - discover
    
    - name: Print mounted devices on hosts
      debug: var="fstab.stdout_lines + [ fstab.stderr ]"
      tags:
        - run
        - discover
```
The `dicover` tag could be use to select tasks. The `never` tag prevents tasks to run by default.
```
$ ansible-playbook -i hosts -u ubuntu quotas.yml --tags "discover"

PLAY [all] *************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************
ok: [51.68.113.239]

TASK [List mounted devices on hosts] ***********************************************************************************************************
changed: [51.68.113.239]

TASK [Print mounted devices on hosts] **********************************************************************************************************
ok: [51.68.113.239] => {
    "fstab.stdout_lines + [ fstab.stderr ]": [
        "LABEL=cloudimg-rootfs / ext4 usrquota,grpquota 0 0",
        "LABEL=UEFI\t/boot/efi\tvfat\tdefaults\t0 0",
        ""
    ]
}

PLAY RECAP *************************************************************************************************************************************
51.68.113.239              : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
The output is not very nice looking but that should be sufficient.

**Comment by pierrepo** [comment]
To cope with multiple hosts, one could add (again) an extra variable in the `hosts` file:
```
[servers]
51.178.95.237 name_server=dev1.plasmabio.org letsencrypt_email=contact@plasmabio.org device_quota=ZZZZZZ
51.178.95.238 name_server=dev2.plasmabio.org letsencrypt_email=contact@plasmabio.org device_quota=WWWW

[servers:vars]
ansible_python_interpreter=/usr/bin/python3
```
@jtpio are you aware of a solution to handle in a better way variables in the `hosts` file?

**Comment by jtpio** [comment]
>  are you aware of a solution to handle in a better way variables in the `hosts` file?

Without adding too much complexity, one option would be to use groups in the `hosts` file: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#inheriting-variable-values-group-variables-for-groups-of-groups

This might require the user of the playbooks to know a bit more on how variables are merged in Ansible.

**Comment by jtpio** [comment]
> An ad-hoc command could be:
> 
> ```
> $ ansible -i hosts -u ubuntu -m command -a "cat /etc/fstab" -o
> ```

An ad-hoc command over SSH otherwise?

```bash
ssh -t ubuntu@dev.plasmabio.org cat /etc/fstab
``` 

(although that would be one host at a time)

**Comment by pierrepo** [comment]
@jtpio would this `hosts` file be a valid one?
```
[plasma1]
51.178.95.237

[plasma1:vars]
ansible_python_interpreter=/usr/bin/python3
name_server=dev1.plasmabio.org
letsencrypt_email=contact@plasmabio.org
device_quota=ZZZZZZ

[plasma2]
51.178.95.238

[plasma2:vars]
ansible_python_interpreter=/usr/bin/python3
name_server=dev2.plasmabio.org
letsencrypt_email=contact@plasmabio.org
device_quota=WWWW
```

- I'd like to avoid the use of `:children`
- `ansible_python_interpreter` and `letsencrypt_email` vars are redundant. This doesn't matter for a few servers and make things clearer (separated for both servers).

Running
```
ansible-playbook site.yml -i hosts -u ubuntu
```
will still apply to both servers?

**Comment by jtpio** [comment]
Yes that one should work.
