### ISSUE TITLE
Move Cockpit doc after user creation

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#141]
Cockpit documentation for installation and configuration is in the *Configuration* section.

We could move it into the *Installation* section, just after the *Creating users on the host* sub-section, since we need both HTTPS and existing users to install and use Cockpit.

**Comment by jtpio** [comment]
Sounds good :+1: 

How about one section after just before *Upgrading*?

**Comment by pierrepo** [comment]
>How about one section after just before Upgrading?

I'm not sure. If Cockpit goes after "Adding Admin Users to JupyterHub", I'm afraid people might be confused with *admin* on the Linux server (that can see/do many things with Cockpit)  and *admin* on the hub...

What do you think?

**Comment by jtpio** [comment]
I was thinking that it could be useful to keep the following section grouped together:

- Monitoring
- Upgrading
- Uninstalling

**Comment by pierrepo** [comment]
> the following sections grouped together

Good idea. As a sub-section of the *Installation* section? Maybe we could also separate the *Backup* from the *Upgrade* in the *Upgrading* subsection. We could then have:

- Monitoring
- Backuping
- Upgrading
- Uninstalling

**Comment by jtpio** [comment]
Since Cockpit is still considered as "optional", we can keep it in the "Configuration" section of the documentation.

So the admins can choose whether they want to use Cockpit or not.

(discussed today with @pierrepo).
