### ISSUE TITLE
Rename to plasma

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasma#154]
To keep it consistent between:

- this repository
- the TLJH plugin
- the documentation
- the twitter account

We can rename and use the name "plasma" to refer to the project itself, instead of "plasmabio":

- [x] the repo becomes: https://github.com/plasmabio/plasma
- [x] the TLJH plugin becomes: `tljh-plasma`
- [x] mentions to "PlasmaBio" in the docs become: "Plasma" (or "PLASMA"?) 
- [x] rename in LICENSE: https://github.com/plasmabio/plasma/blob/b1c8e6d26da368790fe7d8fc04469fe758020587/LICENSE#L3
- [x] update README in https://github.com/plasmabio/tljh-repo2docker: https://github.com/plasmabio/tljh-repo2docker/pull/17
- [x] update readthedocs to https://plasma.readthedocs.io

**Comment by pierrepo** [comment]
>  mentions to "PlasmaBio" in the docs become: "Plasma" (or "PLASMA"?)

I would say "Plasma"
