### ISSUE TITLE
Show build logs when adding an environment?

### ISSUE THREAD

**Issue by lachlancampbell** [plasmabio/plasma#158]
I'm having real trouble adding environments, they fail and I have no information as to why. I can add the plasma templates and a couple of others, but I can't add a repo I branched from the python template for example. Would it be possible to show (like they do on mybinder), or give instructions on how to access the build logs? 

Thanks,
Lachlan.

**Comment by pierrepo** [comment]
Dear @lachlancampbell 
Thank you for your interest in Plasma. There is an [issue](https://github.com/plasmabio/tljh-repo2docker/issues/5) open on this subject in the tljh-repo2docker repo. @jtpio is currently working on it.
You might also want to have a look at the [troubleshooting section](https://docs.plasmabio.org/en/latest/troubleshooting/index.html) in the Plasma doc.

**Comment by lachlancampbell** [comment]
Excellent. Thanks, look forward to using it 👍
