### ISSUE TITLE
Mention tljh-repo2docker in the documentation

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#172]
Plasma uses `tljh-repo2docker`.

It should be a good idea to mention `tljh-repo2docker` in the documentation, essential in the overview:

- in the text
- in the schema

**Comment by pierrepo** [comment]
@jtpio do you mind having a look?

**Comment by jtpio** [comment]
It is mentioned in the User Environments section of the docs: https://docs.plasmabio.org/en/latest/environments/index.html?highlight=tljh-repo2docker#user-environments

And also in this PR: https://github.com/plasmabio/plasma/pull/171

We can add a quick mention in the overview and the diagram.
