### ISSUE TITLE
Unify server parameters in doc

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#175]
In the [HTTP documentation](https://docs.plasmabio.org/en/latest/install/https.html), we advise to provide server parameters in the following format:
```
[servers]
51.178.95.237 name_server=dev1.plasmabio.org letsencrypt_email=contact@plasmabio.org
51.178.95.238 name_server=dev2.plasmabio.org letsencrypt_email=contact@plasmabio.org

[servers:vars]
ansible_python_interpreter=/usr/bin/python3
```

I would prefer we keep server parameters as one parameter per line with the following format:
```
[server1]
51.178.95.237 

[server2]
51.178.95.238

[server1:vars]
ansible_python_interpreter=/usr/bin/python3
name_server=dev1.plasmabio.org
letsencrypt_email=contact@plasmabio.org

[server2:vars]
ansible_python_interpreter=/usr/bin/python3
name_server=dev2.plasmabio.org
letsencrypt_email=contact@plasmabio.org
```

I propose to update the documentation.

**Comment by pierrepo** [comment]
Will you agree @jtpio ?

**Comment by jtpio** [comment]
That sounds reasonable, and possible improvement on https://github.com/plasmabio/plasma/issues/122?

Would you like to open a PR so we can see how it would fit together? Normally the commands to execute the playbooks should stay the same.

**Comment by pierrepo** [comment]
>That sounds reasonable, and a possible improvement on #122?

Exactly.

>Would you like to open a PR so we can see how it would fit together?

Sure

> Normally the commands to execute the playbooks should stay the same.

Indeed. This is the syntax I am using right now ;-)
