### ISSUE TITLE
User home dir path in environment does not reflect the true user home dir path on the system

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#181]
The possibility to have user home directory elsewhere than in `/home` has been recently implemented.

However, in an environment, user home directory path is still `/home/foo` for user `foo` when the true user home directory path is, for instance, `/srv/home/foo`.

**Comment by pierrepo** [comment]
User home directory path in an environment:
```
stu123@99aaad470fe2:~/cours-bash-test$ echo $HOME
/home/stu123
```

User home directory path in the Unix system:
```
stu123@adenine:~$ echo $HOME
/srv/home/stu123
```

**Comment by jtpio** [comment]
Yes it's a leftover from https://github.com/plasmabio/plasma/pull/144

It should be possible to fix this by adding this line:

```python
self.image_homedir_format_string = f"{home}/{username}"
```

After this line here: 

https://github.com/plasmabio/plasma/blob/f0ba4d48ab3234f6da069726a5e8700c4905ce74/tljh-plasma/tljh_plasma/__init__.py#L65

**Comment by pierrepo** [comment]
Thanks @jtpio 
Is it after or **in place** of 
```
self.host_homedir_format_string = f"{home}/{username}" 
```
?

**Comment by pierrepo** [comment]
Could you also please add the appropriate Label :rofl: ?

**Comment by jtpio** [comment]
It would after (a second line), both are needed to specify the path to the home directory on the host and in the container.

So it should look like the following:

```python
self.host_homedir_format_string = f"{home}/{username}" 
self.image_homedir_format_string = f"{home}/{username}"
```

**Comment by pierrepo** [comment]
> It would be after (a second line), 

Sorry. I understood the opposite. Now it's very clear to me. Thanks.

![image](https://user-images.githubusercontent.com/733861/87063240-618a3680-c20e-11ea-8de4-194359e46bdf.png)

Then I cannot escape :smile:
