### ISSUE TITLE
Fix some typos in contributing / documentation

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#182]
The [Contributing](https://docs.plasmabio.org/en/latest/contributing/local.html) part of the documentation explains how to install plasma locally.

To pull the the repo2docker Docker image, the command 
```
docker pull jupyter/repo2docker
```
failed:
```
Using default tag: latest
Error response from daemon: manifest for jupyter/repo2docker:latest not found: manifest unknown: manifest unknown
```

and should be replaced by:
```
docker pull jupyter/repo2docker:master
```

as in [tljh-repo2docker](https://github.com/plasmabio/tljh-repo2docker/blob/master/CONTRIBUTING.md).

**Comment by pierrepo** [comment]
I propose to update the documentation accordingly.

**Comment by jtpio** [comment]
Good catch.

The fix is indeed to change:

```bash
docker pull jupyter/repo2docker
```

By:

```bash
docker pull jupyter/repo2docker:master
```

Here: https://github.com/plasmabio/plasma/blob/master/docs/contributing/local.rst#pull-the-repo2docker-docker-image
