### ISSUE TITLE
Running environment on local plasma/jupyterhub failed with https

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#183]
Following [guidelines](https://docs.plasmabio.org/en/latest/contributing/index.html) to install plasma/jupyterhub locally, I installed all required dependencies and ran plasma/jupyterhub with the command:
```
python3 -m jupyterhub -f jupyterhub_config.py --debug
```
For some reason, opening https://localhost:8000 with a web browser led to this error displayed in the browser:
```
SSL_ERROR_RX_RECORD_TOO_LONG
```

Opening http://localhost:8000 went fine.

I propose to update the documentation accordingly.

**Comment by jtpio** [comment]
Yes, there is no HTTPS when testing locally.

The fix is change:

```
Open https://localhost:8000 in a web browser.
```

For:

```
Open http://localhost:8000 in a web browser.
```

Here: https://github.com/plasmabio/plasma/blob/master/docs/contributing/local.rst#run
