### ISSUE TITLE
Does c.PlasmaSpawner.cmd use conda?

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#186]
The file `tljh-plasma/tljh_plasma/__init__.py` defines variable `c.PlasmaSpawner.cmd` as:
```
c.PlasmaSpawner.cmd = ["/srv/conda/envs/notebook/bin/jupyterhub-singleuser"]
```
However the file `/srv/conda/envs/notebook/bin/jupyterhub-singleuse` does not actually exist on the server.
Should we keep this line?

**Comment by jtpio** [comment]
This should indeed exist and be used to start the single user servers. It is defined in `repo2docker` here: https://github.com/jupyterhub/repo2docker/blob/4363bbe52d5f8e8661a63494959df0b6bbe4f3e0/repo2docker/buildpacks/conda/__init__.py#L35

However the `TODO` here is still relevant:

https://github.com/plasmabio/plasma/blob/7883a6a1266b69ab49f353bdf9974be408bf0709/tljh-plasma/tljh_plasma/__init__.py#L122

And should be kept as mentioned in https://repo2docker.readthedocs.io/en/latest/howto/jupyterhub_images.html.
