### ISSUE TITLE
Enable the journald logging driver to keep user servers logs

### ISSUE THREAD

**Issue by jtpio** [plasmabio/plasma#204]
As mentioned in https://github.com/plasmabio/plasma/pull/200, it would be useful to keep the user server logs around after the server is stopped.

The simplest way of achieving this might be to enable the journald logging drive as mentioned in the Docker documentation:

https://docs.docker.com/config/containers/logging/journald/

**Comment by pierrepo** [comment]
Oh yes that would ne nice.

**Comment by jtpio** [comment]
I opened https://github.com/plasmabio/plasma/pull/205, since this could also help troubleshoot #191.
