### ISSUE TITLE
Why not JupyterLite?

### ISSUE THREAD

**Issue by MRYingLEE** [plasmabio/plasma#223]
JupyterLite is much lighter than The Littlest JupyterHub.

Just curious, why doesn't plasma use JupyterLite instead?

For e-learning purposes, JupyterLite should be good enough to support limited packages.

**Comment by pierrepo** [comment]
Dear @MRYingLEE 

Thank you for your feedbacks. Plasma is used in a large variety of courses, ranging from Python programming to genomics data analysis and processing. Some courses require Python or R packages that are not yet supported by JupyterLite, hence the need for TLJH in addition to specific packages.
